CREATE OR REPLACE PROCEDURE ETL_FACTURACION_PLANES AS
    V_FECHA_INICIO DATE;
    V_FECHA_FIN DATE := TRUNC(SYSDATE); -- Fecha actual
    V_HORA_INICIO_PROCESO DATE := SYSDATE;
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE C##DWH.TBL_FACTURACION_PLANES';
    SELECT MIN(FECHA_COMPRA) INTO V_FECHA_INICIO FROM TBL_FACTURACION_PLANES;
    IF V_FECHA_INICIO IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('No hay datos para procesar.');
        RETURN;
    END IF;
    WHILE V_FECHA_INICIO <= V_FECHA_FIN LOOP
DELETE FROM C##DWH.TBL_FACTURACION_PLANES
WHERE TRUNC(FECHA_COMPRA) = TRUNC(V_FECHA_INICIO);    
    INSERT INTO C##DWH.TBL_FACTURACION_PLANES(
        ID_FACTURACION_PLANES,
        ID_USAURIO,
        ID_TARJETA,
        FECHA_COMPRA,
        NOMBRE_PLAN,
        PRECIO_PLAN,
        DURACION
    )
    SELECT ID_FACTURACION_PLANES,USUARIO, ID_TARJETA,FECHA_COMPRA,
    NOMBRE,PRECIO,DURACION_PLAN  
    FROM TBL_FACTURACION_PLANES A
    INNER JOIN TBL_PLANES B
    ON(A.PLAN = B.ID_PLAN)
    WHERE TRUNC(FECHA_COMPRA) = TRUNC(V_FECHA_INICIO);
    COMMIT;
            V_FECHA_INICIO := V_FECHA_INICIO + 1;
    END LOOP;
END  ETL_FACTURACION_PLANES; 


BEGIN
    ETL_FACTURACION_PLANES; 
END;



SELECT * FROM TBL_PLANES;